name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:latest
          build-args: |
            DATABASE_URL=${{ secrets.DATABASE_URL }}

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          envs: DATABASE_URL
          script: |
            # Přihlášení do GitHub Container Registry
            echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

            # Zastavení a odstranění starého kontejneru
            docker stop webtitan || true
            docker rm webtitan || true

            # Odstranění starého image
            docker image rm ghcr.io/${{ github.repository }}:latest || true

            # Stažení nového image
            docker pull ghcr.io/${{ github.repository }}:latest

            # Vytvoření .env souboru
            cat > /var/www/webtitan.cz/.env << EOL
            DATABASE_URL=${DATABASE_URL}
            NEXT_PUBLIC_URL=https://webtitan.cz
            EOL

            # Spuštění nového kontejneru
            docker run -d \
              --name webtitan \
              --restart always \
              -p 3000:3000 \
              --env-file /var/www/webtitan.cz/.env \
              ghcr.io/${{ github.repository }}:latest
