name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install Dependencies
        run: pnpm install

      - name: Build
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: pnpm build

      - name: Copy files to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          source: ".next,package.json,pnpm-lock.yaml,ecosystem.config.js"
          target: "/var/www/webtitan.cz"
          strip_components: 0

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          envs: DATABASE_URL
          script: |
            cd /var/www/webtitan.cz

            # Nastavení proměnných prostředí
            echo "DATABASE_URL=$DATABASE_URL" >> .env
            echo "HOST=0.0.0.0" >> .env
            echo "HOSTNAME=0.0.0.0" >> .env
            echo "PORT=3000" >> .env
            echo "NEXT_PUBLIC_URL=https://webtitan.cz" >> .env

            # Instalace pouze produkčních závislostí
            pnpm install --prod --frozen-lockfile

            # Zastavení existujícího procesu
            pm2 delete webtitan || true

            # Spuštění nového procesu pomocí ecosystem config
            pm2 start ecosystem.config.js

            # Uložení PM2 konfigurace
            pm2 save

            # Nastavení automatického startu PM2 po rebootu (pouze pokud ještě není nastaveno)
            pm2 startup || true

            # Uložení aktuální konfigurace pro startup
            pm2 save
