name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Copy files to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          source: ".,!node_modules,!.git,!.next"
          target: "/var/www/webtitan.cz"
          strip_components: 0

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        env:
          AUTH_SECRET: ${{ secrets.AUTH_SECRET }}
          AUTH_DISCORD_ID: ${{ secrets.AUTH_DISCORD_ID }}
          AUTH_DISCORD_SECRET: ${{ secrets.AUTH_DISCORD_SECRET }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          envs: AUTH_SECRET,AUTH_DISCORD_ID,AUTH_DISCORD_SECRET,DATABASE_URL
          command_timeout: "20m"
          script: |
            cd /var/www/webtitan.cz
            echo "AUTH_SECRET=$AUTH_SECRET" > .env
            echo "AUTH_DISCORD_ID=$AUTH_DISCORD_ID" >> .env
            echo "AUTH_DISCORD_SECRET=$AUTH_DISCORD_SECRET" >> .env
            echo "DATABASE_URL=$DATABASE_URL" >> .env

            # Instalace pnpm pokud není nainstalován
            if ! command -v pnpm &> /dev/null; then
              npm install -g pnpm
            fi

            # Čistá instalace a build
            pnpm install
            pnpm build
            pm2 restart webtitan
